### PR TITLE
instruments sorted by "order"

### PR DESCRIPTION
**Pull request by settinghead**

### CODE REVIEW

**Comment by settinghead** [comment]
@stulees please review.
@Rise-Vision/delivery FYI. 
Thanks.

**Comment by stulees** [comment]
@settinghead Can you do a version bump and run `gulp build` after. The new version will get updated in the code and I also see some missing changes in the non ES6 file `rise-financial.js`.

**Comment by settinghead** [comment]
@stulees updated with a new version & build.

**Comment by stulees** [comment]
@settinghead Sorry, been a couple merges with a newer version now. Can you rebase and version bump again and `gulp build`.

**Comment by settinghead** [comment]
@stulees no problem. Updated.

**Comment by stulees** [comment]
@settinghead 👍

**Pull request merged**
