### PR TITLE
Get list of instruments from Firebase

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep Looks good. Will we still need the `displayId` property and the logic regarding `displayIdReceived`? Can we remove?

**Comment by donnapep** [comment]
@stulees Funny you should ask. I'd removed it because it wasn't needed for Firebase, but it's needed for the financial data server, so I had to put it all back in. 🙄

**Comment by stulees** [comment]
@donnapep Okay good to know 👍

**Pull request merged**
