### PR TITLE
Commit built files and don't publish to npm

### PR DESCRIPTION
**Pull request by donnapep**
The built files aren't being included with the npm install. After some discussion with Xiyang, it was determined that npm is not a good solution. And with Bower, there doesn't seem to be an easy way to build the files but not commit them. As a result, we'll have to switch back to committing the built files for now.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @settinghead Please review. Thx. @Rise-Vision/delivery

**Comment by stulees** [comment]
@donnapep I think a version bump is needed also as I missed mentioning it when reviewing PR #12 , particularly for this commit - https://goo.gl/NcrQrC.

**Comment by donnapep** [comment]
@stulees Good call. I've bumped the version. Thx.

**Comment by stulees** [comment]
@donnapep You'll have to also run `gulp build` to get the version updated for the files, cheers.

**Comment by donnapep** [comment]
@stulees Oh balls. I rebuilt it. Thx!

**Comment by stulees** [comment]
@donnapep Looks good 👍

**Comment by settinghead** [comment]
:+1:

**Pull request merged**
